s=" Hey there! How are you doing?! "
print(s.lower())
print(s.upper())
print(s.strip())
print(s.isalpha())
print(s.isdigit())
print(s.isspace())
print(s.startswith(' Hey'))
print(s.endswith('doing?! '))
print(s.find('doing'))
print(s.find('other'))
print(s.replace('doing', 'doing mate'))
print(s.split(' '))
print('--'.join(s.split(' ')))
